### ISSUE TITLE
进本第二回合卡住

### ISSUE THREAD

**Issue by SKYisSKYisSKY** [Klamist/FGO-AHK#1]
自动进本以后，第一回合可以正常按照我的预设进行行动，但是第二回合就会卡住不动，也不点战斗，更不能点指令卡。我检查过我的自定义战斗设置，没有错误，应该是可以的

**Comment by Klamist** [comment]
你的战斗流程发我一下我看看？
话说QQ上有回答过你么。。我也不记得了，

**Comment by SKYisSKYisSKY** [comment]
我QQ找过你了，莫事了
在2020年1月28日 18:32，Klamist<notifications@github.com> 写道：

你的战斗流程发我一下我看看？
