### ISSUE TITLE
选助战环节无限循环

### ISSUE THREAD

**Issue by dishuii** [Klamist/FGO-AHK#2]
版本更新后，助战设置cba或者孔明后无法选择了，不停的循环，设为0 任意才能正常运行

**Comment by Price233** [comment]
我这里也是这样，但是我的是孔明可以选择，CBA没办法选择，有办法解决吗？

**Comment by Klamist** [comment]
等我看看是不是头像像素什么的改了……

**Comment by Price233** [comment]
> 等我看看是不是头像像素什么的改了……

 感谢大佬，终于看到了
