### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by zhf883680** [Klamist/FGO-AHK#5]
国服6周年更新结束以后  
支持技能快速释放   
是否只要修改`ssk(si,st:=0)`函数类似如下内容  
```
sleep 300
;等待回到操作界面
if(wstart(1)=0)
```

修改成
随意空白处点击,调整sleep时间就行
```
sleep 100
sclick(1111,66)
;等待回到操作界面
if(wstart(1)=0)

```

**Comment by Klamist** [comment]
这个已经有了，wstart(0或1)就是控制是否等待时连点。
你可以打本的时候注意一下放技能以后的点击情况（虽然现在没更新没法打应该）
