### ISSUE TITLE
6周年版本2个问题

### ISSUE THREAD

**Issue by zhf883680** [Klamist/FGO-AHK#6]
1.点击攻击以后等待时间略长
2.吃苹果那边有点问题，不会自动吃

**Comment by Klamist** [comment]
1. 是指出卡以后，选卡动作等太久了？这个其实是刻意加的延迟，有些低配设备客户端卡的时候快了容易选不到。如果是其他情况，请具体讲一下。
补：原来是选卡界面变快了啊。那我直接减延迟就行了。这样方便
3. 这个我去检查一下。

**Comment by Klamist** [comment]
1.宝具回合等待选卡延迟缩短到0.8秒。
2.连续出击BUG已修复，已更新。吃苹果我这里并不会卡啊，

**Comment by zhf883680** [comment]
我测试了下 能正常流程打了。。感谢！
