### ISSUE TITLE
遊戲版本

### ISSUE THREAD

**Issue by daniel4256x** [Klamist/FGO-AHK#8]
請問台服有辦法運行嗎，開始啟動後會顯示沒有AP

**Comment by Klamist** [comment]
台服是繁体吧？那应该没法……因为里面包含文字识别，没做其他的。

**Comment by daniel4256x** [comment]
> 台服是繁体吧？那应该没法……因为里面包含文字识别，没做其他的

那我有辦法自己改嗎？

**Comment by Klamist** [comment]
感觉很难。有很多像素点，以及助战查找的部分都是依赖对应的文字情况的，要改的很多。或者有办法把台服改成简体中文？但我觉得没必要
这个项目很老了，感觉可以找找其他的，现在应该有不少更简单好用的fgo脚本

**Comment by daniel4256x** [comment]
> 感觉很难。有很多像素点，以及助战查找的部分都是依赖对应的文字情况的，要改的很多。或者有办法把台服改成简体中文？但我觉得没必要 这个项目很老了，感觉可以找找其他的，现在应该有不少更简单好用的fgo脚本
好吧 謝謝你的回應
